---
name: Lint, build and test SRP
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  cpplint:
    name: Run CppLint Check
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run cpplint
        run: |
          /bin/bash ./tools/cpplint/cpplint.sh

  bazel-test:
    name: Run SRP Unit Tests
    needs: cpplint
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Bazel tests
        run: |
          bazel test --nocache_test_results $(bazel query 'kind(cc_test, //...)')

  build:
    needs: bazel-test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build EC package
        run: |
          bazel build --config=bbb-platform //deployment/cpu/ec:pkg

      - name: Build FC package
        run: |
          bazel build --config=bbb-platform //deployment/cpu/fc:pkg

  build-all:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build All
        run: |
          ./tools/build_all/build_all.sh
